version: '3'
services:
  db:
    restart: always
    networks:
      - backend-network
    build:
      context: docker/postgresql
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  api:
    restart: always
    networks:
      - frontend-network
      - backend-network
    build:
      context: backend
    depends_on:
      - db

  web:
    restart: always
    networks:
      - frontend-network
    ports:
      - 80:80
    build:
      context: frontend

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge