# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run:
         name: Show current branch
         command: echo ${CIRCLE_BRANCH}

      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "pom.xml" }}
           - v1-dependencies-

      - run:
         name: Install dependencies
         command: mvn dependency:go-offline

      - save_cache:
         key: v1-dependencies-{{ checksum "pom.xml" }}
         paths:
           - ~/.m2

      - run:
         name: Integration tests
         command: mvn integration-test

      - run:
         name: Checkstyle
         command: mvn checkstyle:checkstyle

      - run:
         name: Generate Code Coverage Report
         command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent -Dmaven.test.failure.ignore=false

      - run:
         name: Run Code Quality Analysis
         command: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=${CIRCLE_BRANCH}

      - run:
         name: Packaging
         command: mvn package

      - store_test_results:
         path: target/surefire-reports