apiVersion: v1
kind: Service
metadata:
  name: {{ include "competency-tree-db.fullname" . }}
  labels:
    {{- include "competency-tree-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "competency-tree-db.selectorLabels" . | nindent 4 }}
