name: maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2.2.0
      with:
        distribution: 'zulu'
        java-version: 16

    - name: Test with maven
      run: mvn -B verify --file pom.xml